In [1]:
# import json

# def read_and_show_json(file_path,signs,output_path):
#     output="{"
#     try:
#         with open(file_path, 'r') as file:
#             json_content = json.load(file)
#             for key, value in json_content.items():
#                 if json.dumps(value["action"][0]) in signs:
#                     output+= '"'+key+'": '+json.dumps(value)+', '
#     except FileNotFoundError:
#         print(f"File not found: {file_path}")
        
#     out = output[:-2]+"}"

#     f = open(output_path, "w")
#     f.write(out)
#     f.close()

#     return out

In [2]:
# json_file_path = 'nslt_100.json'
# output_path = 'nslt_selected.json'
# signs = ["50","51","52","53","54","55","56","57","58","59"]

# out = read_and_show_json(json_file_path,signs,output_path)

# New tasks to implement

"06335": {"subset": "test", "action": [53, 1, 94]}

"Video ID": {"subset": "test/train/val", "action": [wordID, num1, num2]}

Word Id needs to start at 0

count how many videos per word

split the dataset:
    train/set [70/30]
    train/set/val [60/20/20]

## Counting train, test and validation sets

In [1]:
import json
import numpy as np

def countPercent(file_path):
    sets = np.array(["train","test","val"])
    countSets = np.array([0,0,0])
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():
                sample = json.dumps(value["subset"])[1:-1]
                i = np.where(sets == sample)
                countSets[i]+=1
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    return countSets


In [3]:
json_file_path = '../wlasl-complete/nslt_100.json'

sets = countPercent(json_file_path)
print("count of sets [train, test, val]")
print(sets)
print("\nPercentages")
print("train: %.4f"%(sets[0]/sum(sets)*100))
print("test: %.4f"%(sets[1]/sum(sets)*100))
print("val: %.4f"%(sets[2]/sum(sets)*100))

print("\nTotal: %.2f"%((sets[0]/sum(sets)+sets[1]/sum(sets)+sets[2]/sum(sets))*100))

count of sets [train, test, val]
[1442  258  338]

Percentages
train: 70.7556
test: 12.6595
val: 16.5849

Total: 100.00


## Redefining Sets

In [4]:
def countVideos(file_path):
    count = 1
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():
                count+=1
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    return count

In [5]:
def randomArray(N, a, b, c): 
    total_elements = a + b + c
    if total_elements != 100:
        raise ValueError("Percentages should add up to 100.")
    array = ["train"] * (N * a // 100) + ["test"] * (N * b // 100) + ["val"] * (N * c // 100)
    random.shuffle(array)
    return array

In [6]:
def printSets(file_path):
    sets = np.array(["train","test","val"])
    countSets = np.array([0,0,0])
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():
                sample = json.dumps(value["subset"])[1:-1]
                print(sample)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    return countSets

In [7]:
import random 

def redefineSets(test, val, file_path, output_path):
    ids = getVideoIDs(file_path)
    train = 100 - (test+val)
    N = countVideos(file_path)
    randSets = randomArray(N, train, test, val)
    count = 0
    output="{"
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():  
                #str(ids.index(value["action"][0]))
                newValue = '"'+key+'": {"subset": "'+ randSets[count] + '", "action": ['+str(ids.index(value["action"][0])) +', '+str(value["action"][1])+', '+str(value["action"][2])+']}, '
                count+=1
                output += newValue
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    out = output[:-2]+"}"

    f = open(output_path, "w")
    f.write(out)
    f.close()
    return out

In [8]:
def getVideoIDs(file_path):
    ids=[]
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():             
                if value["action"][0] not in ids:
                    ids.append(value["action"][0])
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        
    ids.sort()
    return ids



In [10]:
json_file_path = 'nslt_selected.json'
ids = getVideoIDs(json_file_path)
print(ids)

pos = ids.index(55)
print(pos)

[50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
5


In [11]:
# json_file_path = 'nslt_selected.json'
json_file_path = 'nslt_selected.json'
json_output_path = 'nslt_ajusted.json'
test = 20
val = 20
# train will be 100 - (test + val)
out = redefineSets(test,val, json_file_path,json_output_path)
#print(out)

# checking the new set definitions
sets = countPercent(json_output_path)
print("count of sets [train, test, val]")
print(sets)
print("\nPercentages")
print("train: %.4f"%(sets[0]/sum(sets)*100))
print("test: %.4f"%(sets[1]/sum(sets)*100))
print("val: %.4f"%(sets[2]/sum(sets)*100))

print("\nTotal: %.2f"%((sets[0]/sum(sets)+sets[1]/sum(sets)+sets[2]/sum(sets))*100))

count of sets [train, test, val]
[115  38  38]

Percentages
train: 60.2094
test: 19.8953
val: 19.8953

Total: 100.00


In [2]:
# count percents only

json_output_path = 'nslt_ajusted.json'

sets = countPercent(json_output_path)
print("count of sets [train, test, val]")
print(sets)
print("\nPercentages")
print("train: %.4f"%(sets[0]/sum(sets)*100))
print("test: %.4f"%(sets[1]/sum(sets)*100))
print("val: %.4f"%(sets[2]/sum(sets)*100))

print("\nTotal: %.2f"%((sets[0]/sum(sets)+sets[1]/sum(sets)+sets[2]/sum(sets))*100))

count of sets [train, test, val]
[109  28  26]

Percentages
train: 66.8712
test: 17.1779
val: 15.9509

Total: 100.00


In [2]:
# count percents only
import json
import numpy as np

def countPercent(file_path):
    sets = np.array(["train","test","val"])
    countSets = np.array([0,0,0])
    try:
        with open(file_path, 'r') as file:
            json_content = json.load(file)
            for key, value in json_content.items():
                sample = json.dumps(value["subset"])[1:-1]
                i = np.where(sets == sample)
                countSets[i]+=1
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    return countSets


json_output_path = '../code/i3d/preprocess/nslt_10_01.json'

sets = countPercent(json_output_path)
print("count of sets [train, test, val]")
print(sets)
print("\nPercentages")
print("train: %.4f"%(sets[0]/sum(sets)*100))
print("test: %.4f"%(sets[1]/sum(sets)*100))
print("val: %.4f"%(sets[2]/sum(sets)*100))

print("\nTotal: %.2f"%((sets[0]/sum(sets)+sets[1]/sum(sets)+sets[2]/sum(sets))*100))

count of sets [train, test, val]
[109  28  26]

Percentages
train: 66.8712
test: 17.1779
val: 15.9509

Total: 100.00
